name: Add a project

on:
  issue_comment:
    types: [created, edited]

jobs:
  add-project:
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'add-project') && startsWith(github.event.comment.body, '/draft-pr') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: justfile
      - uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: just bootstrap
      - run: just add-project ${{ github.event.issue.number }}
        env:
          # For GitHub CLI
          GH_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: |
            create-pull-request/patch-for-issue-${{ github.event.issue.number }}
          commit-message: |
            [projects] ${{ github.event.issue.title }}

            Resolves #${{ github.event.issue.number }}
          title: "[projects] ${{ github.event.issue.title }}"
          body: |
            ## What kind of change does this PR introduce?

            - [x] Add a project

            ## Changes

            Resolves #${{ github.event.issue.number }}

            ## Checklist:

            - [ ] I have read the [CONTRIBUTING](https://github.com/best-of-lists/best-of/blob/main/CONTRIBUTING.md) guidelines.
            - [x] I have not modified the `README.md` file. Projects are only supposed to be added or updated within the `projects.yaml` file since the `README.md` file is automatically generated.
          draft: true
